apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  MINIO_ACCESS_KEY: cHJvZHVjdC1zZXJ2aWNlLWtleQ==
  MINIO_SECRET_KEY: cHJvZHVjdC1zZXJ2aWNlLWtleQ==
  MINIO_ENDPOINT: aHR0cDovL21pbmlvOjkwMDA=